"""
Django settings for easyline project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os
from dotenv import dotenv_values
config = dotenv_values('.env')
if not config.get('HOST'):
    config['HOST'] = "mongodb://localhost:27017/"
if not config.get('DATABASENAME'):
    config['DATABASENAME'] = 'easyline'
if not config.get('PORT'):
    config['PORT'] = 27017
if not config.get('USERDB'):
    config['USERDB'] = ''
if not config.get('PASSDB'):
    config['PASSDB'] = ''


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config.get(
    'DJANGO_SECRET_KEY', 'django-insecure-j7!ppc90hmj8296s2wf1_)qgfv28&fq7p_o$ojp4sikg4g9-p*')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config.get('DJANGO_DEBUG', False)

ALLOWED_HOSTS = ['*']


# GEO DJANGO

if os.name == 'nt':

    VIRTUAL_ENV_BASE = os.environ['VIRTUAL_ENV']
    os.environ['PATH'] = os.path.join(
        VIRTUAL_ENV_BASE, r'Lib\site-packages\osgeo') + ';' + os.environ['PATH']
    os.environ['PROJ_LIB'] = os.path.join(
        VIRTUAL_ENV_BASE, r'Lib\site-packages\osgeo\data\proj') + ';' + os.environ['PATH']
    os.environ['GDAL_DATA'] = os.path.join(
        VIRTUAL_ENV_BASE, r"Lib\site-packages\osgeo\data\gdal")
    GDAL_LIBRARY_PATH = os.path.join(
        VIRTUAL_ENV_BASE, r'Lib\site-packages\osgeo\gdal302.dll')

# GEOS_LIBRARY_PATH = r'C:\OSGeo4W\bin\geos_c.dll'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'rest_framework',
    'api.apps.ApiConfig',
    'channels',
    'drf_yasg',
    "django_filters",
    'task.apps.TaskConfig',
    'consumer.apps.ConsumerConfig'

]


# token Settings
JWT_AUTH = {
    'JWT_SECRET_KEY': SECRET_KEY,
    'JWT_ALGORITHM': 'HS256',
    'JWT_VERIFY': True,
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_LEEWAY': 0,
    'JWT_EXPIRATION_DELTA': timedelta(days=2),

    'JWT_ALLOW_REFRESH': True,
    'JWT_REFRESH_EXPIRATION_DELTA': timedelta(days=0),

    'JWT_AUTH_HEADER_PREFIX': 'Bearer',
    'JWT_AUTH_COOKIE': None,

}

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'token': {
            'type': 'apiKey',
            'in': 'header',
            'name': 'Authorization'
        },
    },
    'SUPPORTED_SUBMIT_METHODS': ['get', 'put', 'post', 'patch'],
    'DISPLAY_OPERATION_ID': True,
    'DOC_EXPANSION': 'none',
    'SHOW_REQUEST_HEADERS': True
}

# Rest Framwork
REST_FRAMEWORK = {

    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],

    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication'
    )
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware'
]

ROOT_URLCONF = 'easyline.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages'
            ],
        },
    },
]

WSGI_APPLICATION = 'easyline.wsgi.application'
#
ASGI_APPLICATION = "easyline.asgi.application"
#


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {
        'ENGINE': 'djongo',
        'NAME': config.get('DATABASENAME'),
        'CLIENT': {
            'host': config.get('HOST'),
            # 'port': int(config.get('PORT')),
            # 'username': config.get('USERDB'),
            # 'password': config.get('PASSDB')
        },
    }
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(config.get('REDIS_HOST', '127.0.0.1'), config.get('REDIS_PORT', 6379))],
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


AUTH_USER_MODEL = 'api.User'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Generate logging
# from django.http import UnreadablePostError
import traceback
from django.utils import timezone
import requests
from tabulate import tabulate

def skip_unreadable_post(record):
    try:
        if type(record.args) is tuple:
            return True
        exc_type, exc_value = record.exc_info[:2]
        error = traceback.format_exc()
        result = tabulate([["date",timezone.now().strftime('%d/%m/%y  %H:%M:%S')],["method",record.args.get('method')],["status",record.args.get('status')],["path",record.args.get('path')],["client",record.args.get('client')],["error",error]],tablefmt="grid")
        payload = {
                "content": result,
                "tts": "true"
            }
        print(result)
        if payload.get("content"):
            header = {
            "authorization": "Bot ODE4NDc2MjIxMjgwODEzMDg2.YEYnYQ.IRGH9F0DU4iIWOT7r9DdwZhzJnk"
            }

            r = requests.post("https://discord.com/api/v9/channels/818475844770070529/messages", data=payload,headers=header)   
    except Exception as ex:
        print("Exceptions from settings capture: ", ex)
        
    return True


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'skip_unreadable_posts': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': skip_unreadable_post,
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'WARNING',
            'filters': ['skip_unreadable_posts'],
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],

            'level': 'INFO',
            'propagate': False,
        }
    }
}
