# Generated by Django 3.2.5 on 2022-03-01 01:59

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socketIO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientwebsocket',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='clientwebsocket',
            name='roomID',
            field=models.CharField(default=uuid.UUID('1566c57c-5eea-475e-99cc-86309e505e95'), max_length=200, unique=True),
        ),
    ]
