# Generated by Django 3.2.5 on 2022-03-04 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socketIO', '0002_auto_20220301_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientwebsocket',
            name='roomID',
            field=models.CharField(default=uuid.UUID('d0d949ab-b037-4bd5-ae59-7f37207649e9'), max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='HistoricWebsocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=300)),
                ('roomID', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
