# Generated by Django 3.2.5 on 2022-03-04 02:16

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socketIO', '0003_auto_20220304_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicwebsocket',
            old_name='roomID',
            new_name='sid',
        ),
        migrations.RemoveField(
            model_name='clientwebsocket',
            name='roomID',
        ),
        migrations.AddField(
            model_name='clientwebsocket',
            name='point',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clientwebsocket',
            name='sid',
            field=models.CharField(default=uuid.UUID('7f7f40d8-855e-4911-a28a-1e5f2706c405'), max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='historicwebsocket',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
