# Generated by Django 3.2.5 on 2022-03-04 02:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socketIO', '0004_auto_20220304_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicwebsocket',
            name='complement',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicwebsocket',
            name='point',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientwebsocket',
            name='sid',
            field=models.CharField(default=uuid.UUID('175bf4b3-d558-4bc9-a3b6-064621286702'), max_length=200, unique=True),
        ),
    ]
