# Generated by Django 3.2.5 on 2022-03-04 02:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socketIO', '0005_auto_20220304_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientwebsocket',
            name='sid',
            field=models.CharField(default=uuid.UUID('b90e8bde-17b3-470d-8816-1381bc3a01ad'), max_length=200, unique=True),
        ),
    ]
