# Generated by Django 3.2.5 on 2022-03-04 02:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socketIO', '0006_alter_clientwebsocket_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientwebsocket',
            name='sid',
            field=models.CharField(default=uuid.UUID('cabdff38-ea5c-44a5-ac25-fd9df4f465b7'), max_length=200),
        ),
    ]
