# Generated by Django 3.2.5 on 2022-03-05 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socketIO', '0007_alter_clientwebsocket_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientwebsocket',
            name='sid',
            field=models.CharField(default=uuid.UUID('c2361f70-ed63-4433-9b21-ad326a74aebf'), max_length=200),
        ),
        migrations.AlterField(
            model_name='clientwebsocket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
