# Generated by Django 3.2.5 on 2022-03-14 14:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socketIO', '0008_auto_20220305_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientwebsocket',
            name='sid',
            field=models.CharField(default=uuid.UUID('c846d716-3a0b-4490-9109-84043c1cc601'), max_length=200),
        ),
    ]
