# Generated by Django 3.2.5 on 2021-12-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('ATT', 'atualizado'), ('EP', 'entrou na área do ponto'), ('P', 'penalizado'), ('REM', 'removido'), ('F', 'fundado'), ('ADD', 'adicionado'), ('SP', 'saiu da área do ponto'), ('TRI', 'tripulado'), ('MC', 'movido para cima'), ('T', 'transferido'), ('MB', 'movido para baixo'), ('M', 'mudança de cargo')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('M', 'motorista'), ('P', 'prancheteiro'), ('A', 'admin')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('TRI', 'tripulado'), ('DIS', 'disponivel'), ('IND', 'indisponivel')], default='DIS', max_length=6),
        ),
    ]
