# Generated by Django 3.2.5 on 2021-10-23 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0001_initial'),
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointrow',
            name='link_with_online',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='consumer.client'),
        ),
        migrations.AddField(
            model_name='pointrow',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.point'),
        ),
        migrations.AddField(
            model_name='pointrow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointemployee',
            name='deviceid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.deviceid'),
        ),
        migrations.AddField(
            model_name='pointemployee',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.point'),
        ),
        migrations.AddField(
            model_name='point',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='point',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.plan'),
        ),
        migrations.AddField(
            model_name='historic',
            name='suject',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deviceid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='historicuser',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicpoint',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.point'),
        ),
    ]
