# Generated by Django 3.2.5 on 2021-09-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('REM', 'removido'), ('T', 'transferido'), ('P', 'penalizado'), ('MB', 'movido para baixo'), ('MC', 'movido para cima'), ('ADD', 'adicionado'), ('TRI', 'tripulado'), ('EP', 'entrou no ponto'), ('F', 'fundado'), ('ATT', 'atualizado')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('P', 'prancheteiro'), ('M', 'motorista'), ('A', 'admin')], default='M', max_length=1),
        ),
    ]
