# Generated by Django 3.2.5 on 2021-07-31 15:55

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.FileField(null=True, upload_to=api.models.user_directory_path),
        ),
    ]
