# Generated by Django 3.2.5 on 2021-12-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211212_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('SP', 'saiu da área do ponto'), ('T', 'transferido'), ('ATT', 'atualizado'), ('M', 'mudança de cargo'), ('REM', 'removido'), ('F', 'fundado'), ('TRI', 'tripulado'), ('MC', 'movido para cima'), ('P', 'penalizado'), ('EP', 'entrou na área do ponto'), ('ADD', 'adicionado'), ('MB', 'movido para baixo')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('P', 'prancheteiro'), ('M', 'motorista'), ('A', 'admin')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('DIS', 'disponivel'), ('TRI', 'tripulado'), ('IND', 'indisponivel')], default='DIS', max_length=6),
        ),
    ]
