# Generated by Django 3.2.5 on 2021-10-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('MB', 'movido para baixo'), ('TRI', 'tripulado'), ('SP', 'saiu da área do ponto'), ('EP', 'entrou na área do ponto'), ('REM', 'removido'), ('ADD', 'adicionado'), ('F', 'fundado'), ('MC', 'movido para cima'), ('ATT', 'atualizado'), ('T', 'transferido'), ('P', 'penalizado')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('M', 'motorista'), ('P', 'prancheteiro'), ('A', 'admin')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('TRI', 'tripulado'), ('DIS', 'disponivel'), ('IND', 'indisponivel')], default='DIS', max_length=6),
        ),
    ]
