# Generated by Django 3.2.5 on 2021-09-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210903_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('EP', 'entrou no ponto'), ('P', 'penalizado'), ('T', 'transferido'), ('TRI', 'tripulado'), ('MC', 'movido para cima'), ('F', 'fundado'), ('ATT', 'atualizado'), ('REM', 'removido'), ('MB', 'movido para baixo'), ('ADD', 'adicionado')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('A', 'admin'), ('M', 'motorista'), ('P', 'prancheteiro')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
