# Generated by Django 3.2.5 on 2021-07-31 17:05

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(height_field=200, null=True, upload_to=api.models.user_directory_path, width_field=200),
        ),
    ]
