# Generated by Django 3.2.5 on 2021-10-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211025_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('ATT', 'atualizado'), ('P', 'penalizado'), ('REM', 'removido'), ('MC', 'movido para cima'), ('T', 'transferido'), ('MB', 'movido para baixo'), ('TRI', 'tripulado'), ('F', 'fundado'), ('ADD', 'adicionado'), ('SP', 'saiu da área do ponto'), ('EP', 'entrou na área do ponto')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('P', 'prancheteiro'), ('A', 'admin'), ('M', 'motorista')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('IND', 'indisponivel'), ('TRI', 'tripulado'), ('DIS', 'disponivel')], default='DIS', max_length=6),
        ),
    ]
