# Generated by Django 3.2.5 on 2021-09-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210926_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('MC', 'movido para cima'), ('TRI', 'tripulado'), ('ADD', 'adicionado'), ('T', 'transferido'), ('P', 'penalizado'), ('MB', 'movido para baixo'), ('F', 'fundado'), ('EP', 'entrou no ponto'), ('REM', 'removido'), ('ATT', 'atualizado')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.TextField(null=True),
        ),
    ]
