# Generated by Django 3.2.5 on 2021-10-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210926_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('TRI', 'tripulado'), ('EP', 'entrou no ponto'), ('ADD', 'adicionado'), ('T', 'transferido'), ('MB', 'movido para baixo'), ('F', 'fundado'), ('REM', 'removido'), ('P', 'penalizado'), ('ATT', 'atualizado'), ('MC', 'movido para cima')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('P', 'prancheteiro'), ('A', 'admin'), ('M', 'motorista')], default='M', max_length=1),
        ),
    ]
