# Generated by Django 3.2.5 on 2021-12-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211212_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('M', 'mudança de cargo'), ('MB', 'movido para baixo'), ('ADD', 'adicionado'), ('TRI', 'tripulado'), ('P', 'penalizado'), ('F', 'fundado'), ('MC', 'movido para cima'), ('T', 'transferido'), ('EP', 'entrou na área do ponto'), ('REM', 'removido'), ('ATT', 'atualizado'), ('SP', 'saiu da área do ponto')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('A', 'admin'), ('P', 'prancheteiro'), ('M', 'motorista')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('DIS', 'disponivel'), ('TRI', 'tripulado'), ('IND', 'indisponivel')], default='DIS', max_length=6),
        ),
    ]
