# Generated by Django 3.2.5 on 2021-11-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211027_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('M', 'mudança de cargo'), ('EP', 'entrou na área do ponto'), ('T', 'transferido'), ('P', 'penalizado'), ('F', 'fundado'), ('ADD', 'adicionado'), ('REM', 'removido'), ('ATT', 'atualizado'), ('MC', 'movido para cima'), ('MB', 'movido para baixo'), ('SP', 'saiu da área do ponto'), ('TRI', 'tripulado')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('TRI', 'tripulado'), ('DIS', 'disponivel'), ('IND', 'indisponivel')], default='DIS', max_length=6),
        ),
    ]
