# Generated by Django 3.2.5 on 2021-08-01 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210731_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointrow',
            name='online',
        ),
        migrations.AlterField(
            model_name='historic',
            name='suject',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicpoint',
            name='point',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.point'),
        ),
        migrations.AlterField(
            model_name='historicuser',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pointrow',
            name='position',
            field=models.IntegerField(),
        ),
    ]
