# Generated by Django 3.2.5 on 2021-11-19 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
        ('api', '0005_auto_20211110_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointrow',
            name='link_with_online',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='consumer.client'),
        ),
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('MC', 'movido para cima'), ('ATT', 'atualizado'), ('MB', 'movido para baixo'), ('REM', 'removido'), ('TRI', 'tripulado'), ('EP', 'entrou na área do ponto'), ('P', 'penalizado'), ('F', 'fundado'), ('T', 'transferido'), ('M', 'mudança de cargo'), ('SP', 'saiu da área do ponto'), ('ADD', 'adicionado')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('P', 'prancheteiro'), ('M', 'motorista'), ('A', 'admin')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('DIS', 'disponivel'), ('IND', 'indisponivel'), ('TRI', 'tripulado')], default='DIS', max_length=6),
        ),
    ]
