# Generated by Django 3.2.5 on 2021-10-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211010_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('F', 'fundado'), ('TRI', 'tripulado'), ('REM', 'removido'), ('P', 'penalizado'), ('EP', 'entrou no ponto'), ('MC', 'movido para cima'), ('ATT', 'atualizado'), ('MB', 'movido para baixo'), ('ADD', 'adicionado'), ('T', 'transferido')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('M', 'motorista'), ('P', 'prancheteiro'), ('A', 'admin')], default='M', max_length=1),
        ),
    ]
