# Generated by Django 3.2.5 on 2021-12-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211212_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('ATT', 'atualizado'), ('M', 'mudança de cargo'), ('MB', 'movido para baixo'), ('T', 'transferido'), ('EP', 'entrou na área do ponto'), ('MC', 'movido para cima'), ('F', 'fundado'), ('REM', 'removido'), ('SP', 'saiu da área do ponto'), ('P', 'penalizado'), ('ADD', 'adicionado'), ('TRI', 'tripulado')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('P', 'prancheteiro'), ('A', 'admin'), ('M', 'motorista')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('DIS', 'disponivel'), ('IND', 'indisponivel'), ('TRI', 'tripulado')], default='DIS', max_length=6),
        ),
    ]
