# Generated by Django 3.2.5 on 2022-02-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211212_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('REM', 'removido'), ('SP', 'saiu da área do ponto'), ('EP', 'entrou na área do ponto'), ('ADD', 'adicionado'), ('M', 'mudança de cargo'), ('TRI', 'tripulado'), ('MC', 'movido para cima'), ('MB', 'movido para baixo'), ('F', 'fundado'), ('ATT', 'atualizado'), ('P', 'penalizado'), ('T', 'transferido')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('A', 'admin'), ('M', 'motorista'), ('P', 'prancheteiro')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('DIS', 'disponivel'), ('TRI', 'tripulado'), ('IND', 'indisponivel')], default='DIS', max_length=6),
        ),
    ]
