# Generated by Django 3.2.5 on 2021-11-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211118_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointrow',
            name='link_with_online',
        ),
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('M', 'mudança de cargo'), ('F', 'fundado'), ('T', 'transferido'), ('EP', 'entrou na área do ponto'), ('MC', 'movido para cima'), ('ADD', 'adicionado'), ('TRI', 'tripulado'), ('P', 'penalizado'), ('REM', 'removido'), ('ATT', 'atualizado'), ('SP', 'saiu da área do ponto'), ('MB', 'movido para baixo')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointrow',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('DIS', 'disponivel'), ('TRI', 'tripulado'), ('IND', 'indisponivel')], default='DIS', max_length=6),
        ),
    ]
