# Generated by Django 3.2.5 on 2021-08-01 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210731_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointemployee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
