# Generated by Django 3.2.5 on 2021-10-10 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211010_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('EP', 'entrou no ponto'), ('P', 'penalizado'), ('ADD', 'adicionado'), ('MC', 'movido para cima'), ('T', 'transferido'), ('TRI', 'tripulado'), ('REM', 'removido'), ('F', 'fundado'), ('ATT', 'atualizado'), ('MB', 'movido para baixo')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('P', 'prancheteiro'), ('M', 'motorista'), ('A', 'admin')], default='M', max_length=1),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(default=None, null=True)),
                ('last_login', models.DateTimeField(default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
