# Generated by Django 3.2.5 on 2022-03-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220217_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('SP', 'saiu da área do ponto'), ('MC', 'movido para cima'), ('TRI', 'tripulado'), ('REM', 'removido'), ('EP', 'entrou na área do ponto'), ('M', 'mudança de cargo'), ('MB', 'movido para baixo'), ('P', 'penalizado'), ('ADD', 'adicionado'), ('T', 'transferido'), ('ATT', 'atualizado'), ('F', 'fundado')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('P', 'prancheteiro'), ('A', 'admin'), ('M', 'motorista')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('IND', 'indisponivel'), ('TRI', 'tripulado'), ('DIS', 'disponivel')], default='DIS', max_length=6),
        ),
    ]
