# Generated by Django 3.2.5 on 2021-08-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_pointemployee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointrow',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='point_id',
            field=models.IntegerField(null=True),
        ),
    ]
