# Generated by Django 3.2.5 on 2021-11-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211118_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointrow',
            name='online',
        ),
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('TRI', 'tripulado'), ('T', 'transferido'), ('F', 'fundado'), ('ADD', 'adicionado'), ('MC', 'movido para cima'), ('M', 'mudança de cargo'), ('EP', 'entrou na área do ponto'), ('MB', 'movido para baixo'), ('SP', 'saiu da área do ponto'), ('REM', 'removido'), ('ATT', 'atualizado'), ('P', 'penalizado')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('A', 'admin'), ('P', 'prancheteiro'), ('M', 'motorista')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('IND', 'indisponivel'), ('DIS', 'disponivel'), ('TRI', 'tripulado')], default='DIS', max_length=6),
        ),
    ]
