# Generated by Django 3.2.5 on 2021-10-10 21:23

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211010_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_position',
            field=djongo.models.fields.JSONField(null=True, verbose_name='Ultima Posição (Localização)'),
        ),
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('EP', 'entrou no ponto'), ('TRI', 'tripulado'), ('MB', 'movido para baixo'), ('T', 'transferido'), ('F', 'fundado'), ('MC', 'movido para cima'), ('ATT', 'atualizado'), ('REM', 'removido'), ('P', 'penalizado'), ('ADD', 'adicionado')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('A', 'admin'), ('M', 'motorista'), ('P', 'prancheteiro')], default='M', max_length=1),
        ),
    ]
