# Generated by Django 3.2.5 on 2022-03-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220301_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('EP', 'entrou na área do ponto'), ('MC', 'movido para cima'), ('REM', 'removido'), ('ATT', 'atualizado'), ('T', 'transferido'), ('F', 'fundado'), ('M', 'mudança de cargo'), ('P', 'penalizado'), ('MB', 'movido para baixo'), ('SP', 'saiu da área do ponto'), ('TRI', 'tripulado'), ('ADD', 'adicionado')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('P', 'prancheteiro'), ('M', 'motorista'), ('A', 'admin')], default='M', max_length=1),
        ),
    ]
