# Generated by Django 3.2.5 on 2021-08-01 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210731_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicpoint',
            name='point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.point'),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(default='motorista', max_length=300),
        ),
    ]
