# Generated by Django 3.2.5 on 2021-11-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211119_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('T', 'transferido'), ('M', 'mudança de cargo'), ('SP', 'saiu da área do ponto'), ('TRI', 'tripulado'), ('ADD', 'adicionado'), ('P', 'penalizado'), ('MC', 'movido para cima'), ('ATT', 'atualizado'), ('F', 'fundado'), ('MB', 'movido para baixo'), ('REM', 'removido'), ('EP', 'entrou na área do ponto')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('P', 'prancheteiro'), ('A', 'admin'), ('M', 'motorista')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('DIS', 'disponivel'), ('IND', 'indisponivel'), ('TRI', 'tripulado')], default='DIS', max_length=6),
        ),
    ]
