# Generated by Django 3.2.5 on 2021-10-10 21:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211010_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_position_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('T', 'transferido'), ('MC', 'movido para cima'), ('P', 'penalizado'), ('REM', 'removido'), ('EP', 'entrou no ponto'), ('ADD', 'adicionado'), ('F', 'fundado'), ('TRI', 'tripulado'), ('MB', 'movido para baixo'), ('ATT', 'atualizado')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('P', 'prancheteiro'), ('A', 'admin'), ('M', 'motorista')], default='M', max_length=1),
        ),
    ]
