# Generated by Django 3.2.5 on 2021-08-01 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210801_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicpoint',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.point'),
        ),
    ]
