# Generated by Django 3.2.5 on 2021-11-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211129_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('M', 'mudança de cargo'), ('MB', 'movido para baixo'), ('T', 'transferido'), ('SP', 'saiu da área do ponto'), ('P', 'penalizado'), ('ATT', 'atualizado'), ('REM', 'removido'), ('MC', 'movido para cima'), ('ADD', 'adicionado'), ('F', 'fundado'), ('EP', 'entrou na área do ponto'), ('TRI', 'tripulado')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('A', 'admin'), ('P', 'prancheteiro'), ('M', 'motorista')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('IND', 'indisponivel'), ('TRI', 'tripulado'), ('DIS', 'disponivel')], default='DIS', max_length=6),
        ),
    ]
