# Generated by Django 3.2.5 on 2021-10-11 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
        ('api', '0009_auto_20211010_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointrow',
            name='link_with_online',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='consumer.client'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('DIS', 'disponivel'), ('TRI', 'tripulado'), ('IND', 'indisponivel')], default='DIS', max_length=6),
        ),
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('F', 'fundado'), ('ATT', 'atualizado'), ('SP', 'saiu da área do ponto'), ('EP', 'entrou na área do ponto'), ('REM', 'removido'), ('MB', 'movido para baixo'), ('P', 'penalizado'), ('MC', 'movido para cima'), ('TRI', 'tripulado'), ('ADD', 'adicionado'), ('T', 'transferido')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='historic',
            name='motive',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
