# Generated by Django 3.2.5 on 2022-03-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220301_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('MB', 'movido para baixo'), ('MC', 'movido para cima'), ('M', 'mudança de cargo'), ('REM', 'removido'), ('P', 'penalizado'), ('TRI', 'tripulado'), ('EP', 'entrou na área do ponto'), ('ADD', 'adicionado'), ('ATT', 'atualizado'), ('F', 'fundado'), ('T', 'transferido'), ('SP', 'saiu da área do ponto')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('A', 'admin'), ('M', 'motorista'), ('P', 'prancheteiro')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('TRI', 'tripulado'), ('DIS', 'disponivel'), ('IND', 'indisponivel')], default='DIS', max_length=6),
        ),
    ]
