# Generated by Django 3.2.5 on 2022-03-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220304_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('SP', 'saiu da área do ponto'), ('ADD', 'adicionado'), ('EP', 'entrou na área do ponto'), ('MC', 'movido para cima'), ('TRI', 'tripulado'), ('F', 'fundado'), ('M', 'mudança de cargo'), ('REM', 'removido'), ('MB', 'movido para baixo'), ('P', 'penalizado'), ('T', 'transferido'), ('ATT', 'atualizado')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('A', 'admin'), ('P', 'prancheteiro'), ('M', 'motorista')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('DIS', 'disponivel'), ('TRI', 'tripulado'), ('IND', 'indisponivel')], default='DIS', max_length=6),
        ),
    ]
