# Generated by Django 3.2.5 on 2021-11-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211129_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('MB', 'movido para baixo'), ('ATT', 'atualizado'), ('F', 'fundado'), ('MC', 'movido para cima'), ('T', 'transferido'), ('P', 'penalizado'), ('SP', 'saiu da área do ponto'), ('EP', 'entrou na área do ponto'), ('ADD', 'adicionado'), ('M', 'mudança de cargo'), ('TRI', 'tripulado'), ('REM', 'removido')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('DIS', 'disponivel'), ('IND', 'indisponivel'), ('TRI', 'tripulado')], default='DIS', max_length=6),
        ),
    ]
