# Generated by Django 3.2.5 on 2021-11-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211129_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('MC', 'movido para cima'), ('ATT', 'atualizado'), ('REM', 'removido'), ('T', 'transferido'), ('MB', 'movido para baixo'), ('TRI', 'tripulado'), ('ADD', 'adicionado'), ('EP', 'entrou na área do ponto'), ('M', 'mudança de cargo'), ('P', 'penalizado'), ('F', 'fundado'), ('SP', 'saiu da área do ponto')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('M', 'motorista'), ('A', 'admin'), ('P', 'prancheteiro')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('IND', 'indisponivel'), ('DIS', 'disponivel'), ('TRI', 'tripulado')], default='DIS', max_length=6),
        ),
    ]
