# Generated by Django 3.2.5 on 2022-03-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220304_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('TRI', 'tripulado'), ('P', 'penalizado'), ('SP', 'saiu da área do ponto'), ('MC', 'movido para cima'), ('T', 'transferido'), ('M', 'mudança de cargo'), ('ATT', 'atualizado'), ('ADD', 'adicionado'), ('REM', 'removido'), ('MB', 'movido para baixo'), ('F', 'fundado'), ('EP', 'entrou na área do ponto')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('A', 'admin'), ('M', 'motorista'), ('P', 'prancheteiro')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('DIS', 'disponivel'), ('IND', 'indisponivel'), ('TRI', 'tripulado')], default='DIS', max_length=6),
        ),
    ]
