# Generated by Django 3.2.5 on 2022-03-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220304_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('M', 'mudança de cargo'), ('ADD', 'adicionado'), ('SP', 'saiu da área do ponto'), ('ATT', 'atualizado'), ('P', 'penalizado'), ('F', 'fundado'), ('T', 'transferido'), ('EP', 'entrou na área do ponto'), ('REM', 'removido'), ('TRI', 'tripulado'), ('MB', 'movido para baixo'), ('MC', 'movido para cima')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('M', 'motorista'), ('A', 'admin'), ('P', 'prancheteiro')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('IND', 'indisponivel'), ('DIS', 'disponivel'), ('TRI', 'tripulado')], default='DIS', max_length=6),
        ),
    ]
