# Generated by Django 3.2.5 on 2022-03-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20220304_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('REM', 'removido'), ('MC', 'movido para cima'), ('SP', 'saiu da área do ponto'), ('ATT', 'atualizado'), ('ADD', 'adicionado'), ('EP', 'entrou na área do ponto'), ('F', 'fundado'), ('MB', 'movido para baixo'), ('P', 'penalizado'), ('M', 'mudança de cargo'), ('T', 'transferido'), ('TRI', 'tripulado')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('P', 'prancheteiro'), ('A', 'admin'), ('M', 'motorista')], default='M', max_length=1),
        ),
    ]
