# Generated by Django 3.2.5 on 2021-11-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20211129_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('P', 'penalizado'), ('M', 'mudança de cargo'), ('ADD', 'adicionado'), ('SP', 'saiu da área do ponto'), ('F', 'fundado'), ('MB', 'movido para baixo'), ('REM', 'removido'), ('TRI', 'tripulado'), ('MC', 'movido para cima'), ('EP', 'entrou na área do ponto'), ('ATT', 'atualizado'), ('T', 'transferido')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('A', 'admin'), ('P', 'prancheteiro'), ('M', 'motorista')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('DIS', 'disponivel'), ('IND', 'indisponivel'), ('TRI', 'tripulado')], default='DIS', max_length=6),
        ),
    ]
