# Generated by Django 3.2.5 on 2022-03-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20220304_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('EP', 'entrou na área do ponto'), ('TRI', 'tripulado'), ('F', 'fundado'), ('MC', 'movido para cima'), ('SP', 'saiu da área do ponto'), ('ADD', 'adicionado'), ('ATT', 'atualizado'), ('REM', 'removido'), ('M', 'mudança de cargo'), ('P', 'penalizado'), ('MB', 'movido para baixo'), ('T', 'transferido')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('DIS', 'disponivel'), ('TRI', 'tripulado'), ('IND', 'indisponivel')], default='DIS', max_length=6),
        ),
    ]
