# Generated by Django 3.2.5 on 2022-03-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220305_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('SP', 'saiu da área do ponto'), ('T', 'transferido'), ('ATT', 'atualizado'), ('MC', 'movido para cima'), ('MB', 'movido para baixo'), ('TRI', 'tripulado'), ('M', 'mudança de cargo'), ('REM', 'removido'), ('ADD', 'adicionado'), ('EP', 'entrou na área do ponto'), ('F', 'fundado'), ('P', 'penalizado')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('M', 'motorista'), ('A', 'admin'), ('P', 'prancheteiro')], default='M', max_length=1),
        ),
    ]
