# Generated by Django 3.2.5 on 2021-11-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20211129_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('ADD', 'adicionado'), ('EP', 'entrou na área do ponto'), ('REM', 'removido'), ('SP', 'saiu da área do ponto'), ('T', 'transferido'), ('P', 'penalizado'), ('ATT', 'atualizado'), ('TRI', 'tripulado'), ('MB', 'movido para baixo'), ('F', 'fundado'), ('MC', 'movido para cima'), ('M', 'mudança de cargo')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('M', 'motorista'), ('A', 'admin'), ('P', 'prancheteiro')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('TRI', 'tripulado'), ('DIS', 'disponivel'), ('IND', 'indisponivel')], default='DIS', max_length=6),
        ),
    ]
