# Generated by Django 3.2.5 on 2021-11-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20211129_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('F', 'fundado'), ('SP', 'saiu da área do ponto'), ('TRI', 'tripulado'), ('ADD', 'adicionado'), ('EP', 'entrou na área do ponto'), ('MC', 'movido para cima'), ('P', 'penalizado'), ('ATT', 'atualizado'), ('REM', 'removido'), ('MB', 'movido para baixo'), ('M', 'mudança de cargo'), ('T', 'transferido')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('P', 'prancheteiro'), ('M', 'motorista'), ('A', 'admin')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('TRI', 'tripulado'), ('IND', 'indisponivel'), ('DIS', 'disponivel')], default='DIS', max_length=6),
        ),
    ]
