# Generated by Django 3.2.5 on 2021-11-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20211129_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('REM', 'removido'), ('T', 'transferido'), ('P', 'penalizado'), ('ADD', 'adicionado'), ('TRI', 'tripulado'), ('M', 'mudança de cargo'), ('MB', 'movido para baixo'), ('MC', 'movido para cima'), ('ATT', 'atualizado'), ('F', 'fundado'), ('SP', 'saiu da área do ponto'), ('EP', 'entrou na área do ponto')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('M', 'motorista'), ('P', 'prancheteiro'), ('A', 'admin')], default='M', max_length=1),
        ),
    ]
