# Generated by Django 3.2.5 on 2021-11-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20211130_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('F', 'fundado'), ('M', 'mudança de cargo'), ('MB', 'movido para baixo'), ('REM', 'removido'), ('P', 'penalizado'), ('ATT', 'atualizado'), ('TRI', 'tripulado'), ('SP', 'saiu da área do ponto'), ('EP', 'entrou na área do ponto'), ('ADD', 'adicionado'), ('T', 'transferido'), ('MC', 'movido para cima')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('A', 'admin'), ('P', 'prancheteiro'), ('M', 'motorista')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('DIS', 'disponivel'), ('IND', 'indisponivel'), ('TRI', 'tripulado')], default='DIS', max_length=6),
        ),
    ]
