# Generated by Django 3.2.5 on 2021-11-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20211130_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('M', 'mudança de cargo'), ('REM', 'removido'), ('ADD', 'adicionado'), ('T', 'transferido'), ('ATT', 'atualizado'), ('TRI', 'tripulado'), ('P', 'penalizado'), ('EP', 'entrou na área do ponto'), ('SP', 'saiu da área do ponto'), ('MC', 'movido para cima'), ('MB', 'movido para baixo'), ('F', 'fundado')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('M', 'motorista'), ('A', 'admin'), ('P', 'prancheteiro')], default='M', max_length=1),
        ),
    ]
