# Generated by Django 3.2.5 on 2021-11-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20211130_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('TRI', 'tripulado'), ('REM', 'removido'), ('SP', 'saiu da área do ponto'), ('T', 'transferido'), ('MC', 'movido para cima'), ('ADD', 'adicionado'), ('EP', 'entrou na área do ponto'), ('ATT', 'atualizado'), ('F', 'fundado'), ('MB', 'movido para baixo'), ('M', 'mudança de cargo'), ('P', 'penalizado')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('M', 'motorista'), ('A', 'admin'), ('P', 'prancheteiro')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('TRI', 'tripulado'), ('IND', 'indisponivel'), ('DIS', 'disponivel')], default='DIS', max_length=6),
        ),
    ]
