# Generated by Django 3.2.5 on 2021-11-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20211130_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('M', 'mudança de cargo'), ('MC', 'movido para cima'), ('REM', 'removido'), ('ADD', 'adicionado'), ('TRI', 'tripulado'), ('T', 'transferido'), ('MB', 'movido para baixo'), ('SP', 'saiu da área do ponto'), ('ATT', 'atualizado'), ('P', 'penalizado'), ('EP', 'entrou na área do ponto'), ('F', 'fundado')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('A', 'admin'), ('M', 'motorista'), ('P', 'prancheteiro')], default='M', max_length=1),
        ),
    ]
