# Generated by Django 3.2.5 on 2021-11-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20211130_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('SP', 'saiu da área do ponto'), ('EP', 'entrou na área do ponto'), ('F', 'fundado'), ('REM', 'removido'), ('P', 'penalizado'), ('T', 'transferido'), ('ADD', 'adicionado'), ('ATT', 'atualizado'), ('TRI', 'tripulado'), ('MB', 'movido para baixo'), ('M', 'mudança de cargo'), ('MC', 'movido para cima')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='pointemployee',
            name='function',
            field=models.CharField(choices=[('P', 'prancheteiro'), ('A', 'admin'), ('M', 'motorista')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('DIS', 'disponivel'), ('TRI', 'tripulado'), ('IND', 'indisponivel')], default='DIS', max_length=6),
        ),
    ]
