# Generated by Django 3.2.5 on 2021-11-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20211130_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='action',
            field=models.CharField(choices=[('P', 'penalizado'), ('EP', 'entrou na área do ponto'), ('T', 'transferido'), ('SP', 'saiu da área do ponto'), ('REM', 'removido'), ('ATT', 'atualizado'), ('MB', 'movido para baixo'), ('F', 'fundado'), ('M', 'mudança de cargo'), ('ADD', 'adicionado'), ('TRI', 'tripulado'), ('MC', 'movido para cima')], default='ADD', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('TRI', 'tripulado'), ('DIS', 'disponivel'), ('IND', 'indisponivel')], default='DIS', max_length=6),
        ),
    ]
