@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNWM4NjExNTQ1NGY0MTM2ODRhNTdjYSIsImlhdCI6MTYxNjc2NzE2MSwiZXhwIjoxNjE3MTEyNzYxfQ.LVeOxL7HN2ULl8kqMxcdMHnz_BMuiaqPMZrXVWD88vA
@deviceId = 1
@ip = localhost:4000
@email = admin@wey


#--------------------------------------
#-------------- Registro --------------
#--------------------------------------

POST http://{{ip}}/users/register HTTP/1.1
content-type: application/json

{
	"email": "{{email}}",
	"deviceId":"{{deviceId}}",
 	"name":"Wey",
	"password": "123",
	"admin": false
}

###
#--------------------------------------
#-------------- Login -----------------
#--------------------------------------

POST http://{{ip}}/users/login HTTP/1.1
content-type: application/json

{
	"email": "{{email}}",
	"password": "123"
}

###
#--------------------------------------
#-------------- add point -------------
#--------------------------------------
POST http://{{ip}}/points/useradd HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "email": "wey@wey",
	"deviceId": "{{deviceId}}"
}

###
#--------------------------------------
#-------------- del point -------------
#--------------------------------------
POST http://{{ip}}/points/userdel HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "email": "wey@wey",
	"motivo": "Faz nada",
	"deviceId": "{{deviceId}}"
}

###
