
@ip = localhost:4000
@email = admin@wey
@username = ''
@password = ''
#--------------------------------------
#-------------- Create ----------------
#--------------------------------------

POST http://{{ip}}/plans/create HTTP/1.1
content-type: application/json
Authorization: Basic {{username}}:{{password}}

{
	"name": "",
	"value": 0
}