@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNWM4NjgyNTQ1NGY0MTM2ODRhNTdjZSIsImlhdCI6MTYxNjc2NjE5MCwiZXhwIjoxNjE3MTExNzkwfQ.NaxykONojqTVZd4HDpGJHWer7J4GDIWCbF65RP4tTZo
@deviceId = 2
@ip = localhost:4000


#--------------------------------------
#-------------- Registro --------------
#--------------------------------------

POST http://{{ip}}/users/register HTTP/1.1
content-type: application/json

{
	"email": "teste1@wey",
	"deviceId":3,
 	"name":"Wey",
	"password": "123",
	"admin": false
}

###
#--------------------------------------
#-------------- Login -----------------
#--------------------------------------
POST http://{{ip}}/users/login HTTP/1.1
content-type: application/json

{
	"email": "wey@wey",
	"password": "123"
}

###
#--------------------------------------
#-------------- DATA do usuário -------
#--------------------------------------

POST http://{{ip}}/users/data HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
	"deviceId": "{{deviceId}}"
}

###
#--------------------------------------
#-------------- Update ----------------
#--------------------------------------

POST http://{{ip}}/users/update HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
	"name":"Wey1",
	"password": "",
	"city": "",
	"country": "",
	"vtr": "",
    "deviceId": "{{deviceId}}"
}

###
#--------------------------------------
#-------------- Update ----------------
#--------------------------------------
