# Generated by Django 3.2.5 on 2021-07-13 21:58

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', djongo.models.fields.JSONField(default={'local': []})),
                ('name', models.CharField(max_length=200)),
                ('employee', djongo.models.fields.JSONField(default={'employee': []})),
                ('historic', djongo.models.fields.JSONField(default={'historic': []})),
            ],
        ),
    ]
