# Generated by Django 3.2.5 on 2021-10-23 23:00

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Completed_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('parameters', models.JSONField(blank=True, null=True, verbose_name='Parametros')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de erro')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='')),
                ('expire_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='')),
                ('execute_until', models.DateTimeField(blank=True, default=None, null=True, verbose_name='')),
                ('error', models.BooleanField(default=False)),
                ('finalize_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='')),
                ('repeat', models.IntegerField(default=0, verbose_name='Repeate')),
                ('parameters', models.JSONField(blank=True, null=True, verbose_name='Parametros')),
                ('expire_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='')),
                ('execute_until', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Quando ela irá executar')),
                ('execute_until_interval', models.IntegerField(default=5, verbose_name='Intervalo de atraso da task')),
                ('error', models.BooleanField(default=False, verbose_name='Falhou?')),
                ('complete', models.BooleanField(default=False, verbose_name='Para completar a task')),
            ],
        ),
        migrations.CreateModel(
            name='Task_Until',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='')),
                ('repeat', models.IntegerField(default=0, verbose_name='Repeate')),
                ('parameters', models.JSONField(blank=True, null=True, verbose_name='Parametros')),
                ('expire_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='')),
                ('execute_until', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Quando ela irá executar')),
                ('execute_until_interval', models.IntegerField(default=5, verbose_name='Intervalo de atraso da task')),
                ('error', models.BooleanField(default=False, verbose_name='Falhou?')),
                ('complete', models.BooleanField(default=False, verbose_name='Para completar a task')),
            ],
        ),
    ]
