
# @url =127.0.0.1:8000/api
@url =easyline.ml/api
@email = myTesteradmin1@gmail.com
@pass = mytester123

@deviceid = 71637336233

@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo4LCJ1c2VybmFtZSI6Im5lcHR1bmV4NjNAZ21haWwuY29tIiwiZXhwIjoxNjM5NTM0MDE0LCJlbWFpbCI6Im5lcHR1bmV4NjNAZ21haWwuY29tIiwib3JpZ19pYXQiOjE2MzkzNjEyMTR9.EEgU21FbmsOp0P75R6QfBjNcJqJZKHE6BNAH4R3B8k0


###

POST http://{{url}}/auth/login/ HTTP/1.1
content-type: application/json

{
	"username": "{{email}}",
	"deviceid": {{deviceid}},
	"password": "{{pass}}"
	
}
###

POST http://{{url}}/point/register/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
	"name":"Os Forasteiros 2",
	"city":"Rio de Fevereiro",
	"country":"RJ"
}

###

GET http://{{url}}/point/
Authorization: Bearer {{token}}

###

POST http://{{url}}/point/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
	"point":18
}

###

GET http://{{url}}/point/row/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

###

POST http://{{url}}/point/row/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
	"user": 6
}

###

PUT http://{{url}}/point/row/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
	"user": 13,
	"position": 2
}


