
# @url =127.0.0.1:8000/api
@url =easyline.ml/api
@email = myTesteradmin1@gmail.com
@pass = mytester123

@deviceid = 71637336233

@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo5LCJ1c2VybmFtZSI6InByb3hpbW9AZ21haWwuY29tIiwiZXhwIjoxNjM5NDQ3NjY3LCJlbWFpbCI6InByb3hpbW9AZ21haWwuY29tIiwib3JpZ19pYXQiOjE2MzkyNzQ4Njd9.b2UxKx2dLQmuqSGZDRKnKrQhVQmXo26phHbPE6YxmZg


###

POST http://{{url}}/auth/login/ HTTP/1.1
content-type: application/json

{
	"username": "{{email}}",
	"deviceid": {{deviceid}},
	"password": "{{pass}}"
	
}
###

POST http://{{url}}/point/register/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
	"name":"Os Forasteiros 2",
	"city":"Rio de Fevereiro",
	"country":"RJ"
}

###

GET http://{{url}}/point/
Authorization: Bearer {{token}}

###

POST http://{{url}}/point/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
	"point":12
}

###

GET http://{{url}}/point/row/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

###

POST http://{{url}}/point/row/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
	"user": 6
}

###

PUT http://{{url}}/point/row/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
	"user": 13,
	"position": 2
}


