
@url =127.0.0.1:8000/api
@email = teste2@gmail.com
@pass = sdasdasd

@deviceid = 312312312

@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6InRlc3RlMkBnbWFpbC5jb20iLCJleHAiOjE2MzU3OTk4MTUsImVtYWlsIjoidGVzdGUyQGdtYWlsLmNvbSIsIm9yaWdfaWF0IjoxNjM1NjI3MDE1fQ.I6G94J2MGIn1kS1Y1LNS0qBErSBGPbvRBU3u4q5K0NA


###

POST http://{{url}}/auth/login/ HTTP/1.1
content-type: application/json

{
	"username": "{{email}}",
	"deviceid": {{deviceid}},
	"password": "{{pass}}"
	
}
###

POST http://{{url}}/point/register/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
	"name":"Os Forasteiros 2",
	"city":"Rio de Fevereiro",
	"country":"RJ"
}

###

GET http://{{url}}/point/
Authorization: Bearer {{token}}

###

POST http://{{url}}/point/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
	"id":2
}

