
@url =127.0.0.1:8000/api
@email = admin@admin.com
@pass = admin

@deviceid = 00000000000

@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1NywidXNlcm5hbWUiOiJteVRlc3RlcmFkbWluMUBnbWFpbC5jb20iLCJleHAiOjE2Mzc0NDMxNzcsImVtYWlsIjoibXlUZXN0ZXJhZG1pbjFAZ21haWwuY29tIiwib3JpZ19pYXQiOjE2MzcyNzAzNzd9.Hn7iq7m-ql4LCnwGcuKjtET0LqKU6Y1qjlmLzUIoS38


###

POST http://{{url}}/auth/login/ HTTP/1.1
content-type: application/json

{
	"username": "{{email}}",
  "password": "{{pass}}",
	"deviceid": {{deviceid}}
	
}

###

GET http://{{url}}/admin/config/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

###

PUT http://{{url}}/admin/config/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}


{
  "coordinates": [
    {
      "latitude": 1.96,
      "longitude": 4.57
    },
	{
      "latitude": 6.38,
      "longitude": 7.09
    },
	{
      "latitude": 7.76,
      "longitude": 0.49
    },
	{
      "latitude": 1.72,
      "longitude": 0.23
    },
	{
      "latitude": 1.96,
      "longitude":  4.57
    }
  ]
}

###

DELETE http://{{url}}/admin/config/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

###
POST http://{{url}}/admin/config/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
	"email": "admin@admin.com"
}

###
POST http://{{url}}/admin/actions/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "email": "admin@admin.com",
  "deviceid": "00000000000"
}

###
PUT http://{{url}}/admin/actions/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
	"motive": "Cagou no bnaheiro",
	"suject":{
		"email": "admin@admin.com",
		"deviceid": "00000000000"
	}
}


###

POST http://{{url}}/admin/getHistoric/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "email": "admin@admin.com"
}


###

PUT http://{{url}}/admin/transfer/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "function": "P",
  "email": "myTesterprancheteiro1@gmail.com"
}





