# @url =easyline.ml/api
@url =127.0.0.1:8000/api
@email = teste1@gmail.com
@pass = sdasdasd

@deviceid = 312312312

@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMCwidXNlcm5hbWUiOiJ0ZXN0ZUBnbWFpbC5jb20iLCJleHAiOjE2MzQ2NzY2NjgsImVtYWlsIjoidGVzdGVAZ21haWwuY29tIiwib3JpZ19pYXQiOjE2MzQ1MDM4Njh9.OaQkpeESC8hGpXFkn2d-PdrjZysOgOWOqbk-8CdxzL4

@user_id = 2
###
POST http://{{url}}/auth/register/ HTTP/1.1
content-type: application/json

{
	"email": "{{email}}",
	"deviceid":"{{deviceid}}",
 	"name":"Admin",
	"cpf":"32132132132",
	"password": "{{pass}}",
	"confirm_password": "{{pass}}"
}

###

POST http://{{url}}/auth/refresh/ HTTP/1.1
content-type: application/json

{
	"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMCwidXNlcm5hbWUiOiJ0ZXN0ZUBnbWFpbC5jb20iLCJleHAiOjE2MzQ0OTAyNjQsImVtYWlsIjoidGVzdGVAZ21haWwuY29tIiwib3JpZ19pYXQiOjE2MzQzMTc0NjR9.k0Tm0lULkF2EGixkQbMi81GI7_Iwiv0GAQ_sxwA0ydo"
}

###

POST http://{{url}}/auth/login/ HTTP/1.1
content-type: application/json

{
	"username": "{{email}}",
	"deviceid": "{{deviceid}}",
	"password": "{{pass}}"
	
}

###

POST http://{{url}}/point/register/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
	"name":"Os Forasteiros 2",
	"city":"Rio de Fevereiro",
	"country":"RJ"
}

###

POST http://{{url}}/point/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
	"id":3
}

###

PUT http://{{url}}/point/config/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "coordinates": ["(1.96,4.57)","(6.38,7.09)","(7.76,0.49)","(1.72,0.23)","(0.2,3.29)"]
}

###

GET http://{{url}}/user/
Authorization: Bearer {{token}}


###

GET http://{{url}}/point/
Authorization: Bearer {{token}}

###

GET http://{{url}}/user/historic/
Authorization: Bearer {{token}}

###

GET http://{{url}}/point/historic/
Authorization: Bearer {{token}}


###

GET http://{{url}}/point/historic/{{user_id}}/getHistoricUserQrCode/
Authorization: Bearer {{token}}
