# Generated by Django 3.2.5 on 2021-07-13 21:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
                ('on_created', models.DateField(default=datetime.datetime(2021, 7, 13, 21, 58, 3, 701163, tzinfo=utc))),
                ('permissions', djongo.models.fields.JSONField(default={'permissions': []})),
            ],
        ),
    ]
