# Generated by Django 3.2.5 on 2021-07-13 21:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='on_created',
            field=models.DateField(default=datetime.datetime(2021, 7, 13, 21, 58, 27, 220541, tzinfo=utc)),
        ),
    ]
